### ISSUE TITLE
[General] BeExtlaterality when not in need of bodySite

### ISSUE THREAD

**Issue by annabel-uzl** [hl7-be/core-clinical#36]
We have a Belgium extension [BeExtLaterality ](https://build.fhir.org/ig/hl7-be/core-clinical//StructureDefinition-be-ext-laterality.html) that states the laterality and, from what I understand, can be used on bodySite. 

**Case:** patient has a femur fracture
In this case we don't really need bodySite since it is clear from the definition where the fracture is located. But we do want to include laterality. Do we still use the bodySite element but keep it empty and only use the laterality-extension? Or is there a option that the laterality extension will be added to other elements as well? (dunno if that's a good idea, but just adding some thoughts)

How do we handle this?

**Comment by annabel-uzl** [comment]
EDIT: in context of the datacapabilities project (KWS data to FHIR) this is an urgent question

**Comment by KarlienHL7Belgium** [comment]
bodySite cannot be empty as there is a required binding - confirmed by @costateixeira
