### ISSUE TITLE
BeEncounter v0.2

### ISSUE THREAD

**Issue by annabel-uzl** [hl7-be/core-clinical#67]
Link to Google doc: https://docs.google.com/document/d/1s0eO73DvutWIKOTElGglOf9B4phNlQDV/edit?usp=sharing&ouid=114828987253817454981&rtpof=true&sd=true

Technical issues: please make new github issue
There should be a business WG but we don't need to wait for it and can discuss stuff in the document (or Github issues)

**Comment by bdc-ehealth** [comment]
Create logical model for encounter based on this document: BeEncounter v0.2
